### ISSUE TITLE
Enhance Theme and UI

### ISSUE THREAD

**Issue by DK-Khambhadiya** [DK-Khambhadiya/JS-Drum#1]
- Add user friendly theme
- Add nice UI

**Comment by bloodmonk7** [comment]
I would like to work on it, It will be really nice if you assign it to me

**Comment by DK-Khambhadiya** [comment]
> I would like to work on it, It will be really nice if you assign it to me

Please ask for only one issue.

**Comment by ayobamiseun** [comment]
i will like to work on the styling

**Comment by Vaibhavi-SH** [comment]
I would like to create the best optimize soft ui

**Comment by DK-Khambhadiya** [comment]
Great, I am assigning it to you

**Comment by ayobamiseun** [comment]
> I would like to create the best optimize soft ui

can you follow back i just followed you
